name: Java CI (Gradle)
on: [ push, pull_request ]

jobs:
  build:
    uses: okocraft/workflows/.github/workflows/gradle.yml@v1
    with:
      java-version: '17'
      artifact-directory: "./build/ci-upload"
      build-arguments: "build -P commerce.ci=true"
      package-name: Commerce-Build-${{ github.run_number }}
